# Generated by Django 4.1.7 on 2023-03-31 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название книги')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200, verbose_name='Имя')),
                ('secondname', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('book', models.ManyToManyField(blank=True, related_name='authors', to='author_book.book')),
            ],
        ),
    ]
