# Generated by Django 4.1.7 on 2023-03-31 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='firstname',
            field=models.CharField(max_length=125, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='author',
            name='secondname',
            field=models.CharField(max_length=125, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
