# Generated by Django 4.1.7 on 2023-03-24 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author_book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='secondtname',
            new_name='secondname',
        ),
    ]
