# Generated by Django 4.1.7 on 2023-03-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author_book', '0002_rename_secondtname_author_secondname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='book',
            field=models.ManyToManyField(blank=True, related_name='authors', to='author_book.book'),
        ),
    ]
