# Generated by Django 4.1.7 on 2023-03-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author_book', '0003_alter_author_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='chses',
            field=models.CharField(choices=[('CU', 'cup'), ('SP', 'spoon'), ('FO', 'fork')], default=123123, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название книги'),
        ),
    ]
