# Generated by Django 4.1.7 on 2023-04-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author_book', '0003_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='has_authors',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
