# Generated by Django 4.1.7 on 2023-03-30 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author_book', '0004_book_chses_alter_book_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='chses',
        ),
    ]
